### ISSUE TITLE
v3.0 Task List

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-4e-db#1]
v3.0 aim: On par with online compendium

# Milestone 1 (released) #

**Style**
- [x] Implement content style.
- [x] Rewrite content image to unicode symbols.
- [x] Displayed symbol set demo and selection. (Previously "Add test for replacement symbols and advise on font.")

**Documentation**
- [x] Write documentation on data reterival.
- [x] Copy documentation on data search.

# Milestone 2 (released) #

**UI**
- [x] Make download page displayed status consistent with actual status (currently refresh cat will overwrite).
- [x] Allow re-index extended columns of existing data.
- [x] Allow delete local category.
- [x] Show search result count in category.
- [x] Add "Search Name", "Search Content", "Search Advanced" buttons and disable auto search.
- [x] Fix title bar at top.

**Style**
- [x] Beautify background and buttons.

# Milestone 3 (not released, continue in v3.5) #

**UI**
- [x] Start search only after both search method and category are selected.
- [x] Add buttons to navigate up/down search result.
- [x] Implement dynamic url.
- [x] Apply live language change to title and category names. <br>
~~Use swipe left / right to navigate up / down search result.~~ (Incompatible with non-fixed viewport)

**Functionality**
- [x] Add by-field search.
- [x] Add sorting.
- [x] Add search terms highlight.
- [x] Hide sort columns.
- [x] Update to works with latest compendium and IE 11.

# Alpha #

**UI**
- [ ] Add/Adjust animation, gradiant, shadow, font, and other effects.
- [ ] Improves responsive UI.
- [ ] Add a "loading" screen for loading data, and detect slow locations (e.g. online or extSDCard).

**Functionality**
- [ ] Handle various network error, malform error, missing file errors, without ugly alerts.
- [ ] For non-english localisation, add link to google translate.
- [ ] Refactor and clean up code. <br>
~~Delete local entries that doesn't exist on remote.~~ (With discontinuation of updates, no longer necessary)

# Beta #

**Functionality**
- Fix any outstanding bugs.

**Deployment**
- [ ] Test on IE 9/10/11, Firefox, Chrome, desktop Safari
- [ ] Test on Android browser / Chrom / Opera / Firefox, Mobile Safari.

**Comment by Sheep-y** [comment]
Version 3 discontinued.  Development continues in v3.5.
