### ISSUE TITLE
v3.5x - v3.6 Task List

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-4e-db#16]
# Version 3.5.1 ([Released](https://github.com/Sheep-y/trpg-dnd-4e-db/releases/tag/release%2F3.5.1))

**Style**
- [x] Go through each category and fix entry style.
- [x] Mobile friendly listing layout.

**Functionality**
- [x] List paging with a fixed size of 200 to 1000 rows.
- [x] Preserve filter when changing only search term.

# Version 3.5.2 ([Released](https://github.com/Sheep-y/trpg-dnd-4e-db/releases/tag/release%2F3.5.2))

**Functionality**
- [x] Internal entry linkage.

**Internal**
- [x] Shorten url by dropping category part.
- [x] Consolidate data file to reduce file count.
- [x] Multi-thread indexing and export.
- [x] Merge convert with export to balance disk speed with cpu speed.

# Version 3.5.3 ([Released](https://github.com/Sheep-y/trpg-dnd-4e-db/releases/tag/release%2F3.5.3))

**Functionality**
- [x] Use datalist to support autocomplete in search fields.
- [x] Finish remaining [UI refinements](https://github.com/Sheep-y/trpg-dnd-4e-db/issues/24).
- [x] Add race origins and use as Type in Everything.
- [x] Finish real level and cost filter for items.
- [x] Add csv, tsv, excel, and sql export.
- [x] Update viewer help (typo, grammar, links etc.).
- [x] Highlight column with column filters.
- [x] Record a video walkthrough.

**Internal**
- [x] Refactor converter code to make it cleaner <s>and better safeguard regx match.</s>

# Version ~~3.5.4~~ 3.6

**Functionality**
- [x] Add option to not apply fixes for export.
- [x] Allow export of fixed data.
- [x] Can we add [web app](https://blog.chromium.org/2017/02/integrating-progressive-web-apps-deeply.html) support?
- [x] ~~Explore the possibility of apk export.~~
   Not feasible; need to bundle apk tools to insert assets.  And the UI does not behave like Android.
- [x] Allow to jump directly to item by searching id.
- [x] Support swipe.

**Internal**
- [x] Compress jsonp data to further reduce file size and number.
- [x] Add conversion test cases.
- [x] Load initial data in background in downloader.
- [x] Split more viewer resources out to res folder to reduce size and speed up loading.

**Comment by Sheep-y** [comment]
Closing ticket as 3.6 has finally been released after 10 months of low time.
