### ISSUE TITLE
v3.1 Task List

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-4e-db#2]
Improvements and advanced functions that didn't exist in previous generations 

**Functionality**
- [ ] Multiple result mode.
- [ ] Add parsing of extended columns, such as item levels or power keywords.
- [ ] Build name index and create links from content.
- [ ] App cache update, so that the data can be sync-ed.

**Comment by Sheep-y** [comment]
ActiveX downloader abandoned.  Targets migrated to v3.5 Java downloader.
