### ISSUE TITLE
v3.7 Task List

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-4e-db#35]
# Version 3.7

- [ ] Display multiple results and remove results from display.
- [ ] Try to fit in a race/class/skill filter of feats and powers.  The next killer feature.
- [ ] Document viewer data flow.
- [ ] Document downloader data flow.
